### ISSUE TITLE
Proposition to remove repository

### ISSUE THREAD

**Issue by xavez** [getchopstick/chopstick-settings#1]
Do we still need the settings repo?

I’m confused what the proposed way of working is or what its purpose is. :-)

**Comment by Dietr** [comment]
The reason was so you could run a default chopstick in any project (not just the boilerplate. Similar to how bootstrap works as a dependency? 

But maybe we should group the layers in one repository? Like this one: https://github.com/getchopstick/chopstick

**Comment by xavez** [comment]
I think that would make it much easier to handle and it would probably lower the barrier to entry for new contributors.
